### ISSUE TITLE
About partition flies.

### ISSUE THREAD

**Issue by YuPeize** [RSL-NEU/person-reid-benchmark#12]
Hello, how to get the partition file of Market1501 from the original dataset? Would you share the code? Thanks.

**Comment by NEU-Gou** [comment]
Please downloaded it from here
http://robustsystems.coe.neu.edu/sites/robustsystems.coe.neu.edu/files/systems/code/reid_benchmark/partition/Partition_market.mat

**Comment by YuPeize** [comment]
That's not what I meant. I was curious about how to get the partition file, because we want to do some experiments on our data set. Would you share the code? Thanks!
