### ISSUE TITLE
Don't download market  partition file 

### ISSUE THREAD

**Issue by XiaoDin9** [RSL-NEU/person-reid-benchmark#3]
您好！你们提供的下载market partition file 的网址无效、不能下载，可否麻烦作者提供一下生成partition file的源代码吧，毕竟如果用其他数据就来做这个实验很麻烦，谢谢啦！

**Comment by NEU-Gou** [comment]
Thank you for reporting the bug @XiaoDin9 
The permission issue was fixed and it should be OK now. One of the key reason for this benchmark is that we want everyone can use exactly the same partition to compare the performance. Also it's tricky to write a universal generation function working for all datasets. If you do want the function, I will review the code and release it later.
