### ISSUE TITLE
代码在Market-1501数据集上运行有错误

### ISSUE THREAD

**Issue by XiaoDin9** [RSL-NEU/person-reid-benchmark#4]
使用Market-1501数据集，特征提取采用LOMO，度量学习采用XQDA的方法，出现如下的错误：由于我在服务器上运行的代码，很不方便调试代码，所以把这个错误报到一下：
Start evaluation...
Accuracy: 	Rank1 	Rank5 	Rank10 	Rank20
Number of people in different cameras is inconsistant
Undefined function or variable 's'.

Error in evaluateDis (line 32)
            Res_match{s,pr}(p,junk) = 0;

Error in run_one_experiment (line 195)
        resultStruct = evaluateDis(dis, idx_gallery(pr,:), idx_probe(pr,:), probeID, galleryID, testCamID, mopts, dopts, ropts);
，加之Market-1501数据集很大，提取特征后的相应维度也很大，采用PCA进行降维度得到的识别率很低，不知道什么原因，可否麻烦作者把生成 partition 的这部分源代码共享一下，这样可以节省大家的效率，谢谢啦！

**Comment by NEU-Gou** [comment]
@XiaoDin9 
Sorry for the bug. I'm currently stuck on some other things. Will be back to fix it soon.

**Comment by christianchou** [comment]
嗨，xiaodin9，请问可以邮箱联系一下吗？我有一些关于这份代码的使用问题想问一下你，可以吗？我的邮箱是zhouy268@mail2.sysu.edu.cn

**Comment by NEU-Gou** [comment]
@XiaoDin9 Bugs for Market and PCA have been fixed. Please give it a try. 
For Market dataset with WHOS-6patch feature, linear kLFDA, PCA dim 100, you should obtain this result
r1              r5             r10           r20
40.44 	62.53 	71.50 	79.45
