### ISSUE TITLE
The code for some files is not complete

### ISSUE THREAD

**Issue by yashupian** [RSL-NEU/person-reid-benchmark#8]
Dear author, I find some code is not complete. For example, in file "generatePairs.m":
```
data = 'viper'; %'grid','market','cuhk_detected','prid','ilidsvid'
load(['../FeatureExtraction/feature_' data '_hist_LBP_6patch.mat']);
load(['Split_' data '.mat']);

for s = 1:size(split,1)
    trainID = personID(split(s,1:size(split,2)/2));
    [ix_pos_pair, ix_neg_pair]=GeneratePair(personID,camID,0);
save(['Split_' data '.mat'], 'split',''
```
The last line of the code is obviously not complete.
Could you please send the complete files to me(Email:yashupian@shu.edu.cn) or update the code.
Thank you!

**Comment by NEU-Gou** [comment]
Hi,
 
Sorry for the incomplete code. It won't effect the experiment running. 
If you want to use the pair generation function, please use [this one](https://github.com/RSL-NEU/person-reid-benchmark/blob/master/TrainTestSplits/GeneratePair.m). 
I will delete the incomplete function later. 

Thanks
