### ISSUE TITLE
代码在market数据集上运行报错

### ISSUE THREAD

**Issue by Feesics** [RSL-NEU/person-reid-benchmark#9]
使用market数据集，特征采用ldfv，度量方法用klfda，出现如下错误：
索引超出矩阵维度。

出错 run_one_experiment (line 111)
        [U,mu,vars] = pca(features(idx_train,:)');

出错 run_experiment_benchmark (line 37)
run_one_experiment;
希望作者能够帮忙解决一下，谢谢。

**Comment by NEU-Gou** [comment]
Hi @Feesics, please check the latest commit and give it a try.

**Comment by Feesics** [comment]
Thanks, I will try check it and try again.
